H-8
velvelve/hotel pull request #7
Opened 2023-10-04 05:39 UTC by andreiPavlishin

дал папку components и переместил туду header.
Сверстал header адаптивный

2023-10-04 16:09 UTC, velvelve requested changes
У нас  laravel-проект, нам необходимо создавать соответствующие компоненты. Посмотри [вот тут как это делать ](https://laravel.com/docs/10.x/blade#components)

2023-10-06 23:31 UTC, andreiPavlishin reviewed
Переименовал файл header в header.blade
Добавил доп папку img и assets
Доработал код css

2023-10-07 19:29 UTC, andreiPavlishin reviewed
Доработал header до полного адаптива

2023-10-07 20:03 UTC, andreiPavlishin commented
Подготовил header адаптивный проработал burger menu

2023-10-08 08:32 UTC, velvelve approved these changes

2023-10-08 08:32 UTC, merged